server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: uri-core-api
          uri: lb://URI-CORE-SERVICE
          predicates:
            - Path=/api/**

        - id: uri-core-redirect
          uri: lb://URI-CORE-SERVICE
          predicates:
            - Path=/r/**

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

user-auth-service:
  url: http://localhost:8081  # userAuth-service URL
  endpoints:
    validate: /api/v1/auth/validate
