server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: lb://user-auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: uri-core-api
          uri: lb://URI-CORE-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@tokenKeyResolver}"
                redis-rate-limiter.replenishRate: 1 #TODO:Wont work implement future!
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1

        - id: uri-core-redirect
          uri: lb://URI-CORE-SERVICE
          predicates:
            - Path=/r/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@tokenKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

user-auth-service:
  url: http://localhost:8081  # userAuth-service URL
  endpoints:
    validate: /api/v1/auth/validate

