spring:
  application:
    name: uri-core-service

springdoc:
    default-produces-media-type: application/json

server:
    servlet:
        context-path: /api/v1

application:
  security:
    jwt:
      # secret-key, expiration are typically loaded from config server or environment variables in a real setup
      # For local development, they can be defined here if not overridden.
      # secret-key: your-very-secure-secret-key-for-jwt # Example: replace or load from env
      # expiration: 86400000 # 24 hours in milliseconds for access token, example
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# logging
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
